apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fip-controller
  namespace: fip-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fip-controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fip-controller
    spec:
      containers:
        - name: fip-controller
          image: cbeneke/hcloud-fip-controller:v0.0.6
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - secretRef:
                name:  fip-controller-secrets
          volumeMounts:
            - name: conifg
              mountPath: /app/config
      serviceAccountName: fip-controller
      volumes:
        - name: config
          configMap:
            name: fip-controller-config