apiVersion: v1
kind: ServiceAccount
metadata:
  name: fip-controller
  namespace: fip-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fip-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fip-controller
subjects:
- kind: ServiceAccount
  name: fip-controller
  namespace: fip-controller
